language: node_js
sudo: false
node_js:
- '5.6'
services:
- postgresql
addons:
- postgresql: '9.3'
before_script:
- npm install -g knex
- psql -c 'drop database test;' -U postgres
- psql -c 'create database test;' -U postgres
- npm run migrate_test